nome_carro = input("Digite o nome do carro: ")
valor_carro = float(input("Digite o valor do carro: "))
consumo_por_litro= float(input("Digite o consumo por litro: "))
print("-" * 50)
print(f"| Carro: {nome_carro}")
print(f"| Valor: R$ {valor_carro}")
print(f"| Consumo por litro: {consumo_por_litro} ")
print("-" * 50)